### PR TITLE
A few improvements

### PR DESCRIPTION
**Pull request by leandrosilva**
Hi Pavlo Baron. I've done a few of improvements, so if you think it's good enough, please accept this pull request and update README file accordingly.

Thanks.

### CODE REVIEW

**Comment by pavlobaron** [comment]
hi,

thank you - a lot of work! But still, I have some questions:
- why would you think it's better to collect messages in a concurrent map and so synchronize between several (or many) logging threads, instead of using the pool with a separate Jedis instance, and as far as I understand, a separate Redis connection? What we win right now isn't much more than it was before, since the messages get sent to Redis one-for-one. What really would make sence then is to aggregate them in a batch message. But still, tests are needed with maybe 400 parallel threads (to simulate what a web container would have with thread per request) and to see how much synchronization is going on, compared to a Jedis per thread. Would be pity to log into a clown car having a Ferrari behind :)
- it also needs measurement if one timer thread cleaning up the message map one-for-one woudln't brake the whole thing with many parallel threads. As I did the first throw, I was thinking of two parallel maps or somethings similar, switching between them. Maybe a simple queue pair as well - didn't get to think a lot about it since then

**Comment by leandrosilva** [comment]
Hi Pavlo. I did couple of measurement.

For 2 threads writing 10K messages each:
- Your implementation: 3272175000 ns
- My implementation: 1382538000 ns

For 40 threads writing 10K messages each:
- Your implementation: after 118212000 ns, 8 open connections, and only 12 keys written to Redis, nothing happens anymore; the program just freeze, doesn't go way and doesn't write anything to Redis - if you could tell me what is happening, I'd appreciate too much
- My implementation: 8034594000 ns

If it can help you accept this pull request by any chance, I'd appreciate. Otherwise, no problem sr., I'll respect your decision. At least it was a really cool time to hack on this code.

Thanks.

--- // --- // ---

My code:

```
protected void append(LoggingEvent event) {
    long begin = System.nanoTime();

    try {
        StringBuilder id = new StringBuilder(localHostName);
        id.append(" - ");
        id.append(processName);
        id.append(" - ");
        id.append(Thread.currentThread().getId());
        id.append(" - ");
        id.append(now());
        id.append(" - ");
        id.append(event.getLevel());
        id.append(" - ");
        id.append(UUID.randomUUID());

        messages.put(id.toString(), event.getRenderedMessage());
    } catch (Exception e) {
        //what to do? ignore? send back error - from log???
    }

    long expendHere = System.nanoTime() - begin;
    totalExpend += expendHere;
    System.out.println("Expend here: " + expendHere + " ns");
    System.out.println("Total expend: " + totalExpend + " ns");
}
```

Your code:

```
protected void append(LoggingEvent event) {
    long begin = System.nanoTime();

    //unclear: how about batching events to reduce network gossip?
    try {
        StringBuilder id = new StringBuilder(getLocalHostName());
        id.append(" - ");
        id.append(getProcessName());
        id.append(" - ");
        id.append(Thread.currentThread().getId());
        id.append(" - ");
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        id.append(dateFormat.format(date));
        id.append(" - ");
        id.append(event.getLevel().toString());
        id.append(" - ");
        id.append(UUID.randomUUID().toString());
        getJedis().set(id.toString(), event.getRenderedMessage());
    } catch (Exception e) {
        //what to do? ignore? send back error - from log???
    }

    long expendHere = System.nanoTime() - begin;
    totalExpend += expendHere;
    System.out.println("Expend here: " + expendHere + " ms");
    System.out.println("Total expend: " + totalExpend + " ms");
}
```

Test code (for both):

```
public static void main(String[] args) throws Exception {
    for (int i = 1; i <= 39; i++) {
        new Log4j2RedisTest.LogThread().start();
    }

    for (long i = 0; i < 10000; i++) {
        log.error("that's me " + i);
    }
}
```

**Comment by pavlobaron** [comment]
Hey Leandro. Thanks, I'll  pull your changes later today. We can improve from one code base then, if necessary

Cheers pb

**Comment by pavlobaron** [comment]
And wow, btw, I didn't test with more than 2 threads. I have no idea what's wrong with 12 threads since I just used the jedis pool to get a new connection. Impressive numbers, impressive results, absolutely stupid differences in the behaviour...

**Pull request merged**
